---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - -config.file=/etc/tempo/config.yaml
          ports:
            - containerPort: 3200
              hostPort: 3200
            - containerPort: 4317
              hostPort: 4317
            - containerPort: 4318
              hostPort: 4318
          volumeMounts:
            - name: tempo-data
              mountPath: /var/tempo
            - name: tempo-config
              mountPath: /etc/tempo
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          ports:
            - containerPort: 3000
              hostPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
        - name: prometheus
          image: docker.io/prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver
            - --web.enable-otlp-receiver
            - --enable-feature=exemplar-storage
          ports:
            - containerPort: 9090
              hostPort: 9090
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus
        - name: loki
          image: grafana/loki:latest
          args:
            - -config.file=/etc/loki/config.yaml
          ports:
            - containerPort: 3100
              hostPort: 3100
          volumeMounts:
            - name: loki-data
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki
      volumes:
        - name: tempo-data
          hostPath:
            path: /MALPICA/podman_volumen/tempo
            type: DirectoryOrCreate
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: grafana-data
          hostPath:
            path: /MALPICA/podman_volumen/grafana
            type: DirectoryOrCreate
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: prometheus-data
          hostPath:
            path: /MALPICA/podman_volumen/prometheus
            type: DirectoryOrCreate

        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: loki-data
          hostPath:
            path: /MALPICA/podman_volumen/loki
            type: DirectoryOrCreate
        - name: loki-config
          configMap:
            name: loki-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  config.yaml: |
    stream_over_http_enabled: true

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal

    metrics_generator:
      registry:
        external_labels:
          source: tempo
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://localhost:9090/api/v1/write
            send_exemplars: true
      processor:
        span_metrics: {}
        service_graphs: {}

    overrides:
      defaults:
        metrics_generator:
          processors: [ 'span-metrics', 'service-graphs' ]


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Tempo
        orgId: 1
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus-uid
        access: proxy
        url: http://localhost:9090
        isDefault: false
        jsonData:
          httpMethod: POST
      - name: Loki
        type: loki
        uid: loki-uid
        access: proxy
        url: http://localhost:3100
        isDefault: false
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: "trace_id=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: tempo-uid
      - name: Tempo
        type: tempo
        uid: tempo-uid
        access: proxy
        url: http://localhost:3200
        isDefault: true
        jsonData:
          serviceMap:
            datasourceUid: prometheus-uid
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            datasourceUid: loki-uid
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      allow_structured_metadata: true
      volume_enabled: true


