#extend = "frontend/Makefile.toml"
#[env]
#CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = false

[env]
RUSTFLAGS="-Z macro-backtrace"

[tasks.gitinspector]
workspace = false
script = "gitinspector -HTlrm -F html > gitinspector.html"

[tasks.tailwind]
workspace = false
command = "tailwindcss"
description = "Tailwind CSS, correrlo desde la misma carpeta frontend para que funcione bien"
args = ["--watch", "-i", "./tailwind.css", "-o", "./tailwind-output.css"]
cwd = "frontend"

[tasks.runweb]
workspace = false
command = "trunk"
args = ["serve"]
cwd = "frontend"

[tasks.buildweb]
workspace = false
command = "trunk"
args = ["build"]#, "--release"
cwd = "frontend"

[tasks.deployweb]
workspace = false
command = "firebase"
args = ["deploy"]
cwd = "frontend"

[tasks.runback]
workspace = false
command = "cargo"
args = ["run", "--bin", "medical_back"]

[tasks.buildback]
workspace = false
env = { "RUSTFLAGS" = "-C target-feature=+crt-static" }
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-gnu", "--bin", "medical_back"]#, "--release"

[tasks.backbuildcontainer]
workspace = false
dependencies = ["backbuildrelease"]
command = "docker"
args = ["build", "-t", "medical-back", "."]

[tasks.runbackcontainer]
workspace = false
script = "docker run -p 9000:9000 --rm medical-back:latest"

[tasks.deployback]
workspace = false
script = '''
# gcloud auth configure-docker us-east1-docker.pkg.dev
# docker push [LOCATION]-docker.pkg.dev/[PROJECT-ID]/[REPOSITORY]/[IMAGE]
#
docker tag medical-back:latest us-east1-docker.pkg.dev/miuler-medical-001/medical/medical-back:latest
docker push us-east1-docker.pkg.dev/miuler-medical-001/medical/medical-back:latest
'''

[tasks.build]
command = "cargo"
args = ["build"]
