[workspace]
resolver = "2"
members = ["bin/clickcare", "crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["Hector Miuler Malpica Gallegos <miuler@gmail.com>"]

[workspace.dependencies]
app_core = { path = "crates/core", package = "core" }
user = { path = "crates/user" }
clinic = { path = "crates/clinic" }
clinic_admin = { path = "crates/clinic_admin" }
patient = { path = "crates/patient" }

chrono = "0.4.45"
bon = "3.9.3"
derive-getters = "0.5.0"
regex = "1.13.1"
serde_json = "1.0.151"
ulid = "3.0.0"
thiserror = "2.0.19"
async-trait = "0.1.91"
uuid = { version = "1.24.0", features = ["v4", "v7"] }
dotenvy = "0.15.7"

strum = "0.28.0"
strum_macros = "0.28.0"

## =====================================
## Base de datos
toasty = { version = "0.8.0", features = ["postgresql"] }
sqlx = { version = "0.9.0", features = [
    "json",
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }
postgres = "0.19.14"


## =============================
## Dependencies for gRPC server
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["tokio-macros", "rt-multi-thread"] }
tokio-stream = "0.1.19"
tonic = { version = "0.14.6" }
tonic-reflection = "0.14.6"
tonic-web = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
prost = "0.14.4"
prost-types = "0.14.4"


## =============================
## Observability
log = "0.4.33"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-opentelemetry = "0.33.0"

opentelemetry = { version = "0.32.0", features = ["metrics", "logs"] }
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio", "metrics", "logs"] }
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic", "http-proto", "metrics"] }
opentelemetry-appender-tracing = "0.32.0"
sys-info = "0.9.1"


## =============================
## Test
fake = { version = "5.1.0", features = ["chrono"] }
rstest = "0.26.1"
ctor = "1.0.10"
dtor = "1.0.5"
testcontainers = { version = "0.27.3", features = ["blocking"] }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
