[workspace]
resolver = "2"
members = [
    "bin/clickcare",
    "crates/*"
]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["Hector Miuler Malpica Gallegos <miuler@gmail.com>"]

[workspace.dependencies]
app_core = { path = "crates/core", package = "core" }
user = { path = "crates/user" }
clinic = { path = "crates/clinic" }
clinic_admin = { path = "crates/clinic_admin" }
patient = { path = "crates/patient" }

chrono = "0.4.44"
bon = "3.9.1"
regex = "1.12.3"
serde_json = "1.0.149"
ulid = "1.2.1"
thiserror = "2.0.18"
async-trait = "0.1.89"
uuidv7 = "0.1.7"
uuid = { version = "1.23.0", features = ["v4", "v7"] }
dotenvy = "0.15.7"

strum = "0.28.0"
strum_macros = "0.28.0"

sqlx = { version = "0.8.6", features = ["json", "postgres", "runtime-tokio", "tls-rustls"] }


## =============================
## Dependencies for gRPC server
axum = "0.8.8"
tokio = { version = "1.50.0", features = ["tokio-macros", "rt-multi-thread"] }
tonic = { version = "0.14.5" }
tonic-reflection = "0.14.5"
tonic-web = "0.14.5"
tonic-prost = "0.14.5"
tonic-prost-build = "0.14.5"
prost = "0.14.3"
prost-types = "0.14.3"

## =============================
## Observability
log = "0.4.29"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

## =============================
## Test
fake = { version = "5.1.0", features = ["chrono"] }
rstest = "0.26.1"

