[package]
name = "administration"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
app_core = { path = "../core", package = "core" }
user = { path = "../user" }
thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
uuid.workspace = true
bon.workspace = true
derive-getters.workspace = true
log.workspace = true
tracing.workspace = true
sqlx.workspace = true
apalis.workspace = true
apalis-postgres.workspace = true
