[package]
name = "user"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
app_core.workspace = true

strum.workspace = true
strum_macros.workspace = true
tokio.workspace = true
async-trait.workspace = true
sqlx.workspace = true
log = "0.4.29"
uuid.workspace = true
bon.workspace = true

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
