[package]
name = "clickcare"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clinic = { path = "../clinic" }
clinic_admin = { path = "../clinic_admin" }
patient = { path = "../patient" }

ulid.workspace = true

## =============================
## Dependencies for gRPC server
axum.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-web.workspace = true
tonic-prost.workspace = true
tonic-reflection.workspace = true
prost.workspace = true
prost-types.workspace = true

## =============================
## Observability
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

fake.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true

